name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

    
env:
  DOCKER_PUSH_TOKEN: ${{ secrets.DOCKER_PUSH_TOKEN  }}
  DOCKER_PUSH_ACCOUNT: "kevinaird"
  
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set env
      run: echo "DOCKER_LATEST_TAG=$(date +%s)" >> $GITHUB_ENV
      
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag kevinaird/simple-stats:${DOCKER_LATEST_TAG}
      
    - name: Push to docker hub
      run: |
        docker login -u ${{env.DOCKER_PUSH_ACCOUNT}} -p ${{env.DOCKER_PUSH_TOKEN}}} \
        docker push ${{env.DOCKER_PUSH_ACCOUNT}}/simple-stats:${DOCKER_LATEST_TAG}
